CREATE DATABASE `sistema_limitless`;

USE `sistema_limitless`;

CREATE TABLE `USUARIOS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `TELEFONE` VARCHAR(14) NOT NULL,
  `BAIRRO` VARCHAR(100) NOT NULL,
  `USER` VARCHAR(100) NOT NULL,
  `SENHA` VARCHAR(100) NOT NULL,
  `IMAGEM` BLOB,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USER_UNIQUE` (`USER` ASC) VISIBLE,
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE
)

CREATE TABLE `PRODUTOS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `TAMANHO` VARCHAR(10) NOT NULL, 
  `COR` VARCHAR(20) NOT NULL,
  `ESTADO_PROD` VARCHAR(20) NOT NULL,
  `IMAGEM` BLOB,
  `USUARIO_ID` INT,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
)
;