CREATE DATABASE `sistema_limitless`;

USE `sistema_limitless`;

CREATE TABLE `usuarios` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `TELEFONE` VARCHAR(14) NOT NULL,
  `BAIRRO` VARCHAR(100) NOT NULL,
  `USER` VARCHAR(100) NOT NULL,
  `SENHA` VARCHAR(20)) NOT NULL,
  `IMAGEM` BLOB NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USER_UNIQUE` (`USER` ASC) VISIBLE,
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE
;